/**
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package richtercloud.document.scanner.valuedetection.sutime;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import richtercloud.document.scanner.valuedetectionservice.ValueDetectionServiceConfPanel;
import richtercloud.document.scanner.valuedetectionservice.ValueDetectionServiceConfValidationException;
import richtercloud.message.handler.MessageHandler;

/**
 *
 * @author richter
 */
public class SUTimeValueDetectionServiceConfPanel extends ValueDetectionServiceConfPanel<SUTimeValueDetectionServiceConf> {
    private static final long serialVersionUID = 1L;
    private MessageHandler messageHandler;
    private SUTimeValueDetectionServiceConf serviceConf;
    private final DefaultListModel<String> modelListModel = new DefaultListModel<String>();

    /**
     * Creates new form SUTimeValueDetectionServiceConfPanel
     */
    public SUTimeValueDetectionServiceConfPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelListLabel = new javax.swing.JLabel();
        modelListScrollPane = new javax.swing.JScrollPane();
        modelList = new javax.swing.JList<>();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        modelListLabel.setText("Models:");

        modelList.setModel(modelListModel);
        modelListScrollPane.setViewportView(modelList);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modelListLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modelListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modelListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(modelListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        SUTimeValueDetectionServiceModelAddDialog addDialog = new SUTimeValueDetectionServiceModelAddDialog(SwingUtilities.getWindowAncestor(this),
                messageHandler);
        addDialog.setLocationRelativeTo(this);
        addDialog.setVisible(true);
        String addedPath = addDialog.getAddedPath();
        if(addedPath == null) {
            //dialog canceled
            return;
        }
        this.modelListModel.addElement(addedPath);
        this.serviceConf.getModelJARPathes().add(addedPath);
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        JOptionPane.showConfirmDialog(this, "Not supported, yet -> remove and add new");
    }//GEN-LAST:event_editButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        Object selectedModel = modelList.getSelectedValue();
        this.modelListModel.removeElement(selectedModel);
        this.serviceConf.getModelJARPathes().remove(selectedModel);
    }//GEN-LAST:event_removeButtonActionPerformed

    @Override
    public void init(MessageHandler messageHandler) {
        this.messageHandler = messageHandler;
        this.serviceConf = new SUTimeValueDetectionServiceConf();
    }

    @Override
    public void init(SUTimeValueDetectionServiceConf serviceConf,
            MessageHandler messageHandler) {
        this.messageHandler = messageHandler;
        this.serviceConf = new SUTimeValueDetectionServiceConf(serviceConf.getModelJARPathes());
        for(String modelJARPath : serviceConf.getModelJARPathes()) {
            this.modelListModel.addElement(modelJARPath);
        }
    }

    @Override
    public SUTimeValueDetectionServiceConf getServiceConf() {
        return this.serviceConf;
    }

    @Override
    public void save() throws ValueDetectionServiceConfValidationException {
        this.serviceConf.validate();
    }

    @Override
    public void cancel() {
        //nothing to do
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton editButton;
    private javax.swing.JList<String> modelList;
    private javax.swing.JLabel modelListLabel;
    private javax.swing.JScrollPane modelListScrollPane;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
